[pgagroal]
host = *
port = 5433

log_type = file
log_level = info
log_path = /var/log/pgagroal/pgagroal.log
log_mode = create

log_connections    = on
log_disconnections = on
# log_rotation_size = "3Mb"# in megabytes
# log_rotation_age = 20m   # twenty
log_line_prefix  = "->"

max_connections = 200
idle_timeout = 600
validation = off
unix_socket_dir = /tmp

ev_backend = uring

[openday]
host = pg_database
port = 5432
