---
- hosts: fedora
  gather_facts: false
  tasks:

    - name: Find BARMAN specific files
      delegate_to: 127.0.0.1
      find:
       paths: barman/
       recurse: yes
       file_type: any
       patterns:
         - "*.conf"
         - "*.sh"
         - "*.d"
      register: barman_files


    - name: Copy BARMAN specific files
      become: yes
      with_items:
         - "{{ barman_files.files }}"
      copy:
          src: "{{ item.path }}"
          dest: "{{ item.path | replace( 'barman/', '/' ) }}"
          force: no
          owner: backup
          group: postgres
          mode: '0644'
