---
- hosts: freebsd
  vars:
    http_port: 80
    max_clients: 200
    sudoers_file: /usr/local/etc/sudoers
    pg_version: 12
    pg_software_modules:
      - postgresql{{ pg_version }}-server
      - postgresql{{ pg_version }}-contrib
      - postgresql{{ pg_version }}-client
      - postgresql{{ pg_version }}-plperl
    pg_data_directory: /postgres/{{ pg_version }}/data
    pg_extra_conf_directory: "{{ pg_data_directory }}/conf.d"


  tasks:
    - name: Set hostname {{ inventory_hostname_short }}
      become: yes
      hostname:
        name: "{{ inventory_hostname_short }}"


    - name: Standard packages and applications
      become: yes
      pkgng:
        name:
          - emacs
          - git
          - zsh
          - bash
          - perl5
          - python3
          - sudo
          - doas
          - rsync
          - pstree
          - libxml2
          - libxslt
          - libressl
          - readline
          - gmake
          - gcc
          - nmap
          - p5-App-cpanminus
          - pgbarman
          - htop
          - curl
          - wget
          - libxml2
          - autoconf
        state: latest

    # - hostname:
    #     become: yes
    #     name: miguel
    #     use: freebsd


    - name: Ensure 'wheel' group is present
      become: yes
      group:
        name: wheel
        state: present

    - name: Cross update /etc/hosts with server IP addresses
      become: yes
      with_items: "{{ groups[ 'pg' ] }}"
      lineinfile:
        path: "/etc/hosts"
        regexp: ".*{{ item }}"
        line: "{{ hostvars[ item ].ingress_ipv4 }} \t {{ item }}"
        state: present
        backup: yes
      when: inventory_hostname != item


    - name: PostgreSQL {{ pg_version }}
      become: yes
      pkgng:
        name: "{{ pg_software_modules }}"
        state: latest


    - name: Ensure 'postgres' group is present
      become: yes
      group:
        name: postgres
        state: present

    - name: Ensure PGDATA "{{ pg_data_directory }}" is there
      become: yes
      file:
        path: "{{ pg_data_directory }}"
        owner: postgres
        group: postgres
        mode:  0750
        state: directory

    - name: Check 'luca' user account
      become: yes
      user:
        name: luca
        comment: Luca Ferrari
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        shell: /usr/local/bin/zsh
        groups:
          - wheel
          - postgres


    - name: Allow 'wheel' group to have passwordless sudo
      become: yes
      lineinfile:
        dest: "{{ sudoers_file }}"
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: GitHub personal repositories
      with_items:
        - fluca1978-coding-bits
        - fluca1978-pg-utils
        - pgenv
      git:
        repo: "https://github.com/fluca1978/{{ item }}.git"
        dest: "/home/luca/git/{{ item }}"
        remote: github

    - name: PostgreSQL related packages
      become: yes
      pkgng:
        name:
          - pgxnclient
        state: latest


    - name: copy PostgreSQL boot logo
      become: yes
      with_items:
      - logo-postgresql.lua
      - logo-postgresqlbw.lua
      copy:
        src: freebsd-files/{{ item }}
        dest: /boot/lua
        owner: root
        group: wheel
        mode: '0644'


    - name: Enable PostgreSQL boot logo
      become: yes
      lineinfile:
        dest: /boot/loader.conf
        state: present
        regexp: '^loader_logo'
        line: 'loader_logo="postgresql"'




    - name: copy miscellaneous files in /etc
      become: yes
      with_items:
      - motd
      copy:
        src: freebsd-files/{{ item }}
        dest: /etc
        owner: root
        group: wheel
        mode: '0644'


    - name: Adjusting message of the day (motd)
      become: yes
      lineinfile:
        dest: /etc/motd
        state: present
        regexp: '^     PGDATA'
        line: '     PGDATA = {{ pg_data_directory }}'


    - name: Ensure PGDATA environment variable for user 'luca'
      become: yes
      lineinfile:
        dest: .zshrc
        state: present
        regexp: '^export PGDATA'
        line: 'export PGDATA={{ pg_data_directory }}'

    - name: Creates extra configuration directory for PostgreSQL
      become: yes
      file:
        path: "{{ pg_extra_conf_directory }}"
        state: directory
        owner: postgres
        group: postgres
        mode: 0755

    - name: copy miscellaneous PostgreSQL files in PGDATA
      become: yes
      with_fileglob:
        - "postgresql-files/*"
      copy:
       src: "{{ item }}"
       dest: "{{ pg_extra_conf_directory }}"
       owner: postgres
       group: postgres
       mode: 0660

    - name: Ensure PostgreSQL related files are ready to be activated
      become: yes
      with_fileglob:
        - "postgresql-files/*"
      # with_items:
      #   - basic_logging.conf
      #   - replication.pitr.conf
      #   - replication.barman.conf
      #   - ssl.conf
      lineinfile:
        dest: "{{ pg_data_directory }}/postgresql.conf"
        state: present
        regexp: '^{{ item }}'
        line: '#include_if_exists = {{ pg_extra_conf_directory | basename }}/{{ item | basename }}'


   


    - name: copy PostgreSQL useful scripts
      become: yes
      with_fileglob: freebsd-files/*.conf
      copy:
        src: freebsd-files/{{ item }}
        dest: /usr/local/bin
        owner: root
        group: wheel
        mode: '0755'


    - name: Check 'backup' user account
      become: yes
      user:
       name: backup
       comment: Backup account user
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa
       shell: /bin/sh
       groups:
         - postgres

    - name: Check 'postgres' user account
      become: yes
      user:
       name: postgres
       comment: PostgreSQL server user
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa
       shell: /bin/sh
       groups:
         - postgres


    - name: Sqitch
      with_items:
        - DBD::Pg
        - DBD::SQLite
        - App::Sqitch
      cpanm:
        name: "{{ item }}"

    - name: Ensure pg_hba.conf has a line for replication backup user
      become: yes
      lineinfile:
        dest: "{{ pg_data_directory }}/pg_hba.conf"
        state: present
        create: no
        regexp: 'host    replication     backup           carmensita            trust'
        line: 'host    replication     backup           carmensita            trust'

    - include: pgbackrest.pg.yml

    - name: PostgreSQL Service in rc.conf
      become: yes
      with_items:
        - {
        regexp: "^postgresql_enable",
        line: 'postgresql_enable="YES"'
        }
        - {
        regexp: "^postgresql_data",
        line: 'postgresql_data="{{ pg_data_directory }}"'
        }
      lineinfile:
        dest: /etc/rc.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
