---

- name: Ensure backup directory is there
  become: yes
  with_items:
    - /backup
    - /backup/barman
    - /backup/pgbackrest
    - /var/log/barman
  file:
   path: "{{ item }}"
   state: directory
   owner: backup
   group: barman
   mode:  0755

- name: Find pgbackrest specific files
  delegate_to: 127.0.0.1
  find:
   paths: pgbackrest/
   recurse: yes
   file_type: any
   patterns:
     - "*.conf"
     - "*.sh"
     - "*.d"
  register: pgbackrest_files


- name: Copy pgbackrest specific files
  become: yes
  with_items:
     - "{{ pgbackrest_files.files }}"
  copy:
      src: "{{ item.path }}"
      dest: "{{ item.path | replace( 'pgbackrest/', '/' ) }}"
      force: yes
      owner: backup
      group: postgres
      mode: '0644'



